import tkinter as tk
from tkinter import Menu, Text, Scrollbar, filedialog
import datetime
import random
import os

class App:
    def __init__(self, root):
        self.root = root
        self.root.title("Menu Demo")

        # Initial orange hue
        self.orange_hue = random.randint(0, 255)

        # Menu
        self.menubar = Menu(root)
        self.filemenu = Menu(self.menubar, tearoff=0)
        self.filemenu.add_command(label="Date/Time", command=self.show_date_time)
        self.filemenu.add_command(label="Log to File", command=self.log_to_file)
        self.filemenu.add_command(label="Change Background", command=self.change_background)
        self.filemenu.add_separator()
        self.filemenu.add_command(label="Exit", command=root.quit)
        self.menubar.add_cascade(label="File", menu=self.filemenu)
        root.config(menu=self.menubar)

        # Text box
        self.text_area = Text(root, wrap=tk.WORD)
        self.text_area.pack(expand=True, fill="both")

        # Scrollbar for text area
        self.scrollbar = Scrollbar(root, command=self.text_area.yview)
        self.scrollbar.pack(side="right", fill="y")
        self.text_area['yscrollcommand'] = self.scrollbar.set

    def show_date_time(self):
        now = datetime.datetime.now()
        date_time_string = now.strftime("%Y-%m-%d %H:%M:%S")
        self.text_area.insert(tk.END, date_time_string + "\n")
        self.text_area.see(tk.END)


    def log_to_file(self):
        content = self.text_area.get("1.0", tk.END)
        if content.strip(): # Only write if there's content
            try:
                with open("log.txt", "a") as file:
                    file.write(content)
                    self.text_area.delete("1.0", tk.END) # Clear after writing
                    #print("Content written to log.txt") # Optional confirmation message
            except Exception as e:
                print(f"Error writing to file: {e}")
        else:
            print("Text box is empty. Nothing to log.")

    def change_background(self):
        color = "#{:02x}{:02x}{:02x}".format(self.orange_hue, self.orange_hue // 2, 0)  # Orange hue
        self.root.configure(bg=color)
        self.text_area.configure(bg=color)

if __name__ == "__main__":
    root = tk.Tk()
    app = App(root)
    root.geometry("600x400")
    root.mainloop()
